on:
  issue_comment:
    types: [ created ]

jobs:
  delete_job:
    # This job only runs for pull request comments
    name: Delete comments job
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout step
        uses: actions/checkout@v2
      - name: Delete step
        uses: ./.github/actions/delete-comments
