on:
  issue_comment:
    types: [ created ]

jobs:
  delete_job:
    name: Delete comments job
    # This job only runs for comments by sonarcloud[bot]
    if: ${{ github.event.comment.user.login == 'balakine' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout step
      uses: actions/checkout@v2
    - name: Delete step
      uses: ./.github/actions/delete-comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BLAH3: ${{ github.event.comment.user.login }}
