name: Delete comment

on:
  issue_comment:
    types: [ created ]

jobs:
  delete_job:
    name: Delete comments job
    # This job only runs for comments by sonarcloud[bot]
    if: ${{ github.event.comment.user.login == 'balakine' }}
    runs-on: ubuntu-latest
    steps:

    - name: Delete step
      uses: balakine/public-action-subfolder@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
